version: "3"
services: 
  node: 
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nodejs
    volumes: 
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - "18833:18833"
      - "1883:1883"
    
volumes:
  node_modules:

networks:
  default:
    external:
      name: iot-laravel-webserver_app-network
